version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    assignees:
      - "strfl89"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
